# Generated by Django 4.0.6 on 2022-09-07 03:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 9, 6, 23, 25, 14, 184625))),
                ('update_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EscuelaProgramaDepartamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=5, verbose_name='Código')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Modalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 9, 6, 23, 25, 14, 184625))),
                ('update_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 9, 6, 23, 25, 14, 186626))),
                ('update_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=5, verbose_name='Código')),
                ('nombre', models.CharField(max_length=250, verbose_name='Nombre')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 9, 6, 23, 25, 14, 183625))),
                ('update_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sigla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 9, 6, 23, 25, 14, 184625))),
                ('update_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDisciplinar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 9, 6, 23, 25, 14, 185627))),
                ('update_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoHabilitacionTrayectoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 9, 6, 23, 25, 14, 185627))),
                ('update_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadSolicitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 9, 6, 23, 25, 14, 185627))),
                ('update_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_unico_historico', models.CharField(max_length=250, null=True, verbose_name='Código Único')),
                ('anio', models.IntegerField(default='1900', verbose_name='Año')),
                ('periodo', models.CharField(max_length=50, verbose_name='Periodo')),
                ('curso_habilitacion', models.CharField(max_length=150, verbose_name='Curso Habilitación')),
                ('horas', models.IntegerField(default='0', verbose_name='Horas')),
                ('mes_fin', models.DateTimeField(default=datetime.datetime(2022, 9, 6, 23, 25, 14, 186626))),
                ('seccion', models.CharField(max_length=50, verbose_name='Sección')),
                ('observacion', models.CharField(max_length=150, verbose_name='Observación')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 9, 6, 23, 25, 14, 186626))),
                ('update_at', models.DateTimeField(null=True)),
                ('cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='historic_register.cargo')),
                ('escuela_programa_departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='historic_register.escuelaprogramadepartamento')),
            ],
        ),
    ]
