# Generated by Django 4.0.6 on 2022-10-04 02:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historic_register', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrohistorico',
            name='curso_habilitacion',
        ),
        migrations.RemoveField(
            model_name='registrohistorico',
            name='horas',
        ),
        migrations.RemoveField(
            model_name='registrohistorico',
            name='rol',
        ),
        migrations.RemoveField(
            model_name='registrohistorico',
            name='tipo_disciplinar',
        ),
        migrations.RemoveField(
            model_name='registrohistorico',
            name='tipo_habilitacion_trayectoria',
        ),
        migrations.RemoveField(
            model_name='registrohistorico',
            name='unidad_solicitante',
        ),
        migrations.AddField(
            model_name='registrohistorico',
            name='a_cargo',
            field=models.CharField(default=0, max_length=250, verbose_name='A Cargo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registrohistorico',
            name='accion_formativa',
            field=models.CharField(default=0, max_length=250, verbose_name='Acción Formativa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registrohistorico',
            name='duracion_horas',
            field=models.IntegerField(default='0', verbose_name='Duración Horas'),
        ),
        migrations.AddField(
            model_name='registrohistorico',
            name='estrategia_formativa',
            field=models.CharField(default=0, max_length=250, verbose_name='Estatregia Formativa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registrohistorico',
            name='mencion',
            field=models.CharField(default=0, max_length=250, verbose_name='Mención'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registrohistorico',
            name='ruta',
            field=models.CharField(default=0, max_length=250, verbose_name='Ruta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registrohistorico',
            name='trayectoria',
            field=models.CharField(default=0, max_length=250, verbose_name='Trayectoria'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registrohistorico',
            name='cargo',
            field=models.CharField(default=0, max_length=100, verbose_name='Cargo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registrohistorico',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 3, 23, 52, 24, 368264)),
        ),
        migrations.AlterField(
            model_name='registrohistorico',
            name='estado',
            field=models.CharField(default=0, max_length=100, verbose_name='Estado'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registrohistorico',
            name='mes_fin',
            field=models.CharField(max_length=50, verbose_name='Mes Fin'),
        ),
        migrations.AlterField(
            model_name='registrohistorico',
            name='modalidad',
            field=models.CharField(max_length=100, verbose_name='Modalidad'),
        ),
        migrations.AlterField(
            model_name='registrohistorico',
            name='observacion',
            field=models.CharField(max_length=250, verbose_name='Observación'),
        ),
        migrations.AlterField(
            model_name='registrohistorico',
            name='proveedor',
            field=models.CharField(max_length=250, verbose_name='Proveedor'),
        ),
        migrations.AlterField(
            model_name='registrohistorico',
            name='seccion',
            field=models.CharField(max_length=100, verbose_name='Sección'),
        ),
        migrations.AlterField(
            model_name='registrohistorico',
            name='sigla',
            field=models.CharField(max_length=50, verbose_name='Sigla'),
        ),
        migrations.AlterField(
            model_name='sede',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 3, 23, 52, 24, 365278)),
        ),
        migrations.DeleteModel(
            name='Cargo',
        ),
        migrations.DeleteModel(
            name='Modalidad',
        ),
        migrations.DeleteModel(
            name='Proveedor',
        ),
        migrations.DeleteModel(
            name='Sigla',
        ),
        migrations.DeleteModel(
            name='TipoDisciplinar',
        ),
        migrations.DeleteModel(
            name='TipoHabilitacionTrayectoria',
        ),
        migrations.DeleteModel(
            name='UnidadSolicitante',
        ),
    ]
